name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test

    steps:
    - uses: actions/checkout@v1
      name: Check out repository
    - uses: actions/setup-node@v1
      name: Set up Node.js
      with:
        node-version: 12

    - name: yarn install, build and test
      run: |
        yarn install
        yarn build
        yarn test
